stages:
  - build
  # - deploy

build_image:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
      command: ["--insecure-registry=registry.gitlab.com"]
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
  script:
    - docker build -t ${CONTAINER_IMAGE} .
  after_script:
    - docker push ${CONTAINER_IMAGE}
