## Requirements

- name: Send notification message via Slack
  slack:
    token: TATK1HJTB/BAUL4JQHF/7OVChtq1C3UeskboFRWwwd1D
    msg: 'wedding.giarrizzo.fr Deploy start'

- name: Nginx root web folders creation
  file:
    path: "/home/web/giarrizzo.fr/wedding/"
    owner: bruno
    group: www-data
    state: directory
    mode: 0755

- name: Nginx log folders creation
  file:
    path: "/var/log/nginx/wedding.giarrizzo.fr/"
    owner: www-data
    group: adm
    state: directory
    mode: 0755

## vHost Config

- name: Site Install = Wedding.Giarrizzo.fr
  template:
    src: wedding.giarrizzo.fr.conf
    dest: /etc/nginx/sites-enabled/005-wedding.giarrizzo.fr.conf
  notify: restart nginx

## Git Pull

- name: Git pull - wedding.giarrizzo.fr
  git:
    repo: git@gitlab.com:bgiarrizzo/wedding.giarrizzo.fr.git
    dest: /home/web/giarrizzo.fr/wedding/
    update: yes

- name: Send notification message via Slack
  slack:
    token: TATK1HJTB/BAUL4JQHF/7OVChtq1C3UeskboFRWwwd1D
    msg: 'wedding.giarrizzo.fr Deploy finished'
